namespace = "github.com/rur/userrolesadmin"
page = "admin"

[views]

  [views.home]
    name = "home"
    doc = "Landing page of the site"
    uri = "/"

    [views.home.blocks]

      [[views.home.blocks.nav]]
        name = "home-nav"
        default = true
        doc = "principle navigation"
        handler = "treetop.Constant(\"ok\")"

      [[views.home.blocks.wrapper]]
        name = "landing"
        default = true
        doc = "General admin search area"
        path = "/"

        [views.home.blocks.wrapper.blocks]

          [[views.home.blocks.wrapper.blocks.landing-results]]
            name = "home-user-search-results"
            path = "/user-search"

          [[views.home.blocks.wrapper.blocks.landing-results]]
            name = "home-role-search-results"
            path = "/role-search"

  [views.history]
    name = "history"
    doc = "Land on current days activity by default"
    uri = "/history"

    [views.history.blocks]

      [[views.history.blocks.nav]]
        name = "history-nav"
        default = true

      [[views.history.blocks.wrapper]]
        name = "history-search"
        default = true
        doc = "Allow history log to be searched"
        path = "/history"

  [views.account]
    name = "account"
    doc = "View and edit user account information. Admin controls also."
    uri = "/account"

    [views.account.blocks]

      [[views.account.blocks.nav]]
        name = "account-nav"
        default = true

      [[views.account.blocks.wrapper]]
        name = "account-landing"
        default = true
        doc = "Administer admin user account"
        path = "/account"

  [views.user]
    name = "user"
    doc = "View and edit user roles"
    uri = "/users"

    [views.user.blocks]

      [[views.user.blocks.nav]]
        name = "user-nav"
        default = true

      [[views.user.blocks.nav]]
        name = "user-nav2"

      [[views.user.blocks.wrapper]]
        name = "all-users"
        default = true
        path = "/users"

      [[views.user.blocks.wrapper]]
        name = "user-info"
        doc = "Display user information"
        path = "/users/{user}"

        [views.user.blocks.wrapper.blocks]

          [[views.user.blocks.wrapper.blocks.content]]
            default = true
            name = "user-roles-list"
            path = "/users/{user}/roles"
            includes = [ "user > user-nav" ]

          [[views.user.blocks.wrapper.blocks.content]]
            name = "user-roles-edit"
            path = "/users/{user}/edit"
            includes = [ "user > user-nav2" ]

          [[views.user.blocks.wrapper.blocks.content]]
            name = "user-assign-roles"
            path = "/users/{user}/assign"
            includes = [ "user > user-nav2" ]

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "user-find-roles-results"
            path = "/users/{user}/find-role-roles"
            includes = [ "user > user-nav" ]

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "user-assign-role-submit"
            path = "/users/{user}/assign-roles-submit"
            includes = [ "user > user-nav2" ]
            method = "POST"

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "user-revoke-role-submit"
            path = "/users/{user}/revoke-roles-submit"
            includes = [ "user > user-nav" ]
            method = "POST"

  [views.role]
    name = "role"
    doc = "View and edit role membership list"
    uri = "/roles"

    [views.role.blocks]

      [[views.role.blocks.nav]]
        name = "role-nav"
        default = true

      [[views.role.blocks.nav]]
        name = "role-nav2"

      [[views.role.blocks.wrapper]]
        name = "all-roles"
        doc = "show summary of all roles"
        default = true
        path = "/roles"

      [[views.role.blocks.wrapper]]
        name = "role-wrapper"
        path = "/roles/{role}"
        merge = "testing-gen-merge"

        [views.role.blocks.wrapper.blocks]

          [[views.role.blocks.wrapper.blocks.content]]
            default = true
            name = "role-users-list"
            path = "/roles/{role}/users"
            includes = [ "role > role-nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            name = "role-users-edit"
            path = "/roles/{role}/edit"
            includes = [ "role > role-nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            name = "role-assign-users"
            path = "/roles/{role}/assign"
            includes = [ "role > role-nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "role-assign-results-roles"
            path = "/roles/{role}/find-user-roles-results"
            includes = [ "role > role-nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "role-assign-results-users"
            path = "/roles/{role}/find-users-results"
            includes = [ "role > role-nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "role-assign-role-complete"
            path = "/roles/{role}/assign-role-users-complete"
            includes = [ "role > role-nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "role-revoke-users-complete"
            path = "/roles/{role}/assign-users-complete"
            includes = [ "role > role-nav" ]