namespace = "github.com/rur/userrolesadmin"
page = "admin"

[views]

  [views.home]
    name = "home"
    doc = "Landing page of the site"
    uri = "/"

    [views.home.blocks]

      [[views.home.blocks.nav]]
        name = "nav"
        default = true
        doc = "principle navigatio"
        handler = "treetop.Constant(\"ok\")"

      [[views.home.blocks.wrapper]]
        name = "landing"
        default = true
        doc = "General admin search area"
        path = "/"

        [views.home.blocks.wrapper.blocks]

          [[views.home.blocks.wrapper.blocks.landing-results]]
            name = "user-search-results"
            path = "/user-search"

          [[views.home.blocks.wrapper.blocks.landing-results]]
            name = "role-search-results"
            path = "/role-search"

  [views.history]
    name = "history"
    doc = "Land on current days activity by default"
    uri = "/history"

    [views.history.blocks]

      [[views.history.blocks.nav]]
        name = "nav"
        default = true

      [[views.history.blocks.wrapper]]
        name = "search"
        default = true
        doc = "Allow history log to be searched"
        path = "/history"

  [views.account]
    name = "account"
    doc = "View and edit user account information. Admin controls also."
    uri = "/account"

    [views.account.blocks]

      [[views.account.blocks.nav]]
        name = "nav"
        default = true

      [[views.account.blocks.wrapper]]
        name = "landing"
        default = true
        doc = "Administer admin user account"
        path = "/account"

  [views.user]
    name = "user"
    doc = "View and edit user roles"
    uri = "/users"

    [views.user.blocks]

      [[views.user.blocks.nav]]
        name = "nav"
        default = true

      [[views.user.blocks.nav]]
        name = "nav2"

      [[views.user.blocks.wrapper]]
        name = "all-users"
        default = true
        path = "/users"

      [[views.user.blocks.wrapper]]
        name = "base"
        doc = "Display user information"
        path = "/users/{user}"

        [views.user.blocks.wrapper.blocks]

          [[views.user.blocks.wrapper.blocks.content]]
            default = true
            name = "roles-list"
            path = "/users/{user}/roles"
            includes = [ "user > nav" ]

          [[views.user.blocks.wrapper.blocks.content]]
            name = "roles-edit"
            path = "/users/{user}/edit"
            includes = [ "user > nav2" ]

          [[views.user.blocks.wrapper.blocks.content]]
            name = "assign-roles"
            path = "/users/{user}/assign"
            includes = [ "user > nav2" ]

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "find-roles-results"
            path = "/users/{user}/find-role-roles"
            includes = [ "user > nav" ]

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "assign-role-complete"
            path = "/users/{user}/assign-roles-complete"
            includes = [ "user > nav2" ]

          [[views.user.blocks.wrapper.blocks.content]]
            fragment = true
            name = "revoke-role-complete"
            path = "/users/{user}/revoke-roles-complete"
            includes = [ "user > nav" ]

  [views.role]
    name = "role"
    doc = "View and edit role membership list"
    uri = "/roles"

    [views.role.blocks]

      [[views.role.blocks.nav]]
        name = "nav"
        default = true

      [[views.role.blocks.nav]]
        name = "nav2"

      [[views.role.blocks.wrapper]]
        name = "all-roles"
        doc = "show summary of all roles"
        default = true
        path = "/roles"

      [[views.role.blocks.wrapper]]
        name = "role"
        path = "/roles/{role}"
        merge = "testing-gen-merge"

        [views.role.blocks.wrapper.blocks]

          [[views.role.blocks.wrapper.blocks.content]]
            default = true
            name = "users-list"
            path = "/roles/{role}/users"
            includes = [ "role > nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            name = "users-edit"
            path = "/roles/{role}/edit"
            includes = [ "role > nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            name = "assign-users"
            path = "/roles/{role}/assign"
            includes = [ "role > nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "assign-results-roles"
            path = "/roles/{role}/find-user-roles-results"
            includes = [ "role > nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "assign-results-users"
            path = "/roles/{role}/find-users-results"
            includes = [ "role > nav" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "assign-role-complete"
            path = "/roles/{role}/assign-role-users-complete"
            includes = [ "role > nav2" ]

          [[views.role.blocks.wrapper.blocks.content]]
            fragment = true
            name = "revoke-users-complete"
            path = "/roles/{role}/assign-users-complete"
            includes = [ "role > nav" ]