namespace: github.com/rur/userrolesadmin
page: admin
views:
  home:
    name: home
    doc: Landing page of the site
    uri: /
    blocks:
      nav:
        - name: home-nav
          default: true
          doc: principle navigation
          handler: treetop.Constant("ok")
      wrapper:
        - name: landing
          default: true
          doc: General admin search area
          path: /
          blocks:
            landing-results:
              - name: home-user-search-results
                path: /user-search
              - name: home-role-search-results
                path: /role-search
  history:
    name: history
    doc: Land on current days activity by default
    uri: /history
    blocks:
      nav:
        - name: history-nav
          default: true
      wrapper:
        - name: history-search
          default: true
          doc: Allow history log to be searched
          path: /history
  account:
    name: account
    doc: View and edit user account information. Admin controls also.
    uri: /account
    blocks:
      nav:
        - name: account-nav
          default: true
      wrapper:
        - name: account-landing
          default: true
          doc: Administer admin user account
          path: /account
  user:
    name: user
    doc: View and edit user roles
    uri: /users
    blocks:
      nav:
        - name: user-nav
          default: true
        - name: user-nav2
      wrapper:
        - name: all-users
          default: true
          path: /users
        - name: user-info
          doc: Display user information
          path: '/users/{user}'
          blocks:
            content:
              - default: true
                name: user-roles-list
                path: '/users/{user}/roles'
                includes:
                  - user > user-nav
              - name: user-roles-edit
                path: '/users/{user}/edit'
                includes:
                  - user > user-nav2
              - name: user-assign-roles
                path: '/users/{user}/assign'
                includes:
                  - user > user-nav2
              - fragment: true
                name: user-find-roles-results
                path: '/users/{user}/find-role-roles'
                includes:
                  - user > user-nav
              - fragment: true
                name: user-assign-role-submit
                path: '/users/{user}/assign-roles-submit'
                includes:
                  - user > user-nav2
                method: POST
              - fragment: true
                name: user-revoke-role-submit
                path: '/users/{user}/revoke-roles-submit'
                includes:
                  - user > user-nav
                method: POST
  role:
    name: role
    doc: View and edit role membership list
    uri: /roles
    blocks:
      nav:
        - name: role-nav
          default: true
        - name: role-nav2
      wrapper:
        - name: all-roles
          doc: show summary of all roles
          default: true
          path: /roles
        - name: role-wrapper
          path: '/roles/{role}'
          merge: testing-gen-merge
          blocks:
            content:
              - default: true
                name: role-users-list
                path: '/roles/{role}/users'
                includes:
                  - role > role-nav
              - name: role-users-edit
                path: '/roles/{role}/edit'
                includes:
                  - role > role-nav2
              - name: role-assign-users
                path: '/roles/{role}/assign'
                includes:
                  - role > role-nav
              - fragment: true
                name: role-assign-results-roles
                path: '/roles/{role}/find-user-roles-results'
                includes:
                  - role > role-nav2
              - fragment: true
                name: role-assign-results-users
                path: '/roles/{role}/find-users-results'
                includes:
                  - role > role-nav
              - fragment: true
                name: role-assign-role-complete
                path: '/roles/{role}/assign-role-users-complete'
                includes:
                  - role > role-nav2
              - fragment: true
                name: role-revoke-users-complete
                path: '/roles/{role}/assign-users-complete'
                includes:
                  - role > role-nav
