namespace: github.com/rur/userrolesadmin
page: admin
views:
  home:
    name: home
    doc: Landing page of the site
    uri: /
    blocks:
      nav:
        - name: nav
          default: true
          doc: principle navigatio
          handler: treetop.Constant("ok")

      wrapper:
        - name: landing
          default: true
          doc: General admin search area
          path: /
          blocks:
            landing-results:
              - name: user-search-results
                path: /user-search

              - name: role-search-results
                path: /role-search

  history:
    name: history
    doc: Land on current days activity by default
    uri: /history
    blocks:
      nav:
        - name: nav
          default: true

      wrapper:
        - name: search
          default: true
          doc: Allow history log to be searched
          path: /history

  account:
    name: account
    doc: View and edit user account information. Admin controls also.
    uri: /account
    blocks:
      nav:
        - name: nav
          default: true

      wrapper:
        - name: landing
          default: true
          doc: Administer admin user account
          path: /account


  user:
    name: user
    doc: View and edit user roles
    uri: /users
    blocks:
      nav:
        - name: nav
          default: true

        - name: nav2

      wrapper:
        - name: all-users
          default: true
          path: /users

        - name: base
          doc: Display user information
          path: /users/{user}
          blocks:
            content:
              - default: true
                name: roles-list
                path: /users/{user}/roles
                includes:
                  - user > nav

              - name: roles-edit
                path: /users/{user}/edit
                includes:
                  - user > nav2

              - name: assign-roles
                path: /users/{user}/assign
                includes:
                  - user > nav2

              - fragment: true
                name: find-roles-results
                path: /users/{user}/find-role-roles
                includes:
                  - user > nav

              - fragment: true
                name: assign-role-complete
                path: /users/{user}/assign-roles-complete
                includes:
                  - user > nav2

              - fragment: true
                name: revoke-role-complete
                path: /users/{user}/revoke-roles-complete
                includes:
                  - user > nav

  role:
    name: role
    doc: View and edit role membership list
    uri: /roles
    blocks:
      nav:
        - name: nav
          default: true

        - name: nav2

      wrapper:
        - name: all-roles
          doc: show summary of all roles
          default: true
          path: /roles

        - name: role
          path: /roles/{role}
          merge: testing-gen-merge
          blocks:
            content:
              - default: true
                name: users-list
                path: /roles/{role}/users
                includes:
                  - role > nav

              - name: users-edit
                path: /roles/{role}/edit
                includes:
                  - role > nav2

              - name: assign-users
                path: /roles/{role}/assign
                includes:
                  - role > nav

              - fragment: true
                name: assign-results-roles
                path: /roles/{role}/find-user-roles-results
                includes:
                  - role > nav2

              - fragment: true
                name: assign-results-users
                path: /roles/{role}/find-users-results
                includes:
                  - role > nav

              - fragment: true
                name: assign-role-complete
                path: /roles/{role}/assign-role-users-complete
                includes:
                  - role > nav2

              - fragment: true
                name: revoke-users-complete
                path: /roles/{role}/assign-users-complete
                includes:
                  - role > nav
